Added sliding window functionality, testing on elife data
InsanallyLab/DecodingPackage pull request #7
Opened 2024-08-06 22:55 UTC by Samvitti

Added sliding window functionality to `ndecoder.py, session.py`.

2024-09-12 20:09 UTC, badralbanna requested changes

2024-09-12 20:09 UTC, badralbanna commented on decoder/io/load_elife_sliding.py
> +                            if nose_poke_time > trial_start + 2.5:
Just include this is as a constant at the top of the script.

2024-09-12 20:09 UTC, badralbanna commented on decoder/io/load_elife_sliding.py
>                              index = (nose_poke_times > trial_start)
So I'm curious if you think it would be worth it do be able to do this programmatically like you feed a bunch of spike times and event times and a function to classify session end and it would return a Unique interval set.

2024-09-12 21:39 UTC, Samvitti commented on __pycache__/decoding.cpython-38.pyc
Hmm *.pyc is already in the .gitignore ... not sure why it didn't ignore .pyc files in this commit.

2024-09-12 21:42 UTC, Samvitti commented on decoder/io/load_elife_sliding.py
>                              index = (nose_poke_times > trial_start)
I think it would definitely be worth it! I've been prioritising figuring out the discrepancy between my code's results and the elife paper results, but once that gets sorted I can add this functionality.

2024-09-13 12:23 UTC, badralbanna commented
Once you've added something you need to use git rm --cached to get it out of the index. .gitignore just excludes a file from git status and git add *.
On Sep 12, 2024 at 5:39 PM -0400, Samvitti ***@***.***>, wrote:
> @Samvitti commented on this pull request.
> On __pycache__/decoding.cpython-38.pyc:
> Hmm *.pyc is already in the .gitignore ... not sure why it didn't ignore .pyc files in this commit.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because your review was requested.Message ID: ***@***.***>

2024-09-13 12:24 UTC, badralbanna commented
Sounds good!
On Sep 12, 2024 at 5:42 PM -0400, Samvitti ***@***.***>, wrote:
> @Samvitti commented on this pull request.
> In decoder/io/load_elife_sliding.py:
> > @@ -76,12 +76,18 @@
>                             index = (nose_poke_times > trial_start)
> I think it would definitely be worth it! I've been prioritising figuring out the discrepancy between my code's results and the elife paper results, but once that gets sorted I can add this functionality.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because your review was requested.Message ID: ***@***.***>

2025-01-28 03:28 UTC, badralbanna approved these changes
I wasn't able to go over everything in great detail, but looking through it looked very good. Thank you for all your hard work on this!

2025-01-28 03:28 UTC, badralbanna commented on decoder/core/ndecoder.py
> +# def calculate_circular_MSE(self,
Would it make sense to just remove this? Is there a reason it's commented out?

2025-01-28 03:53 UTC, Samvitti commented on decoder/core/ndecoder.py
> +# def calculate_circular_MSE(self,
Yes, I can remove it! It was my code for calculating circular MSE for the monkey dataset but it doesn't have any use for the elife dataset.

2025-01-28 23:29 UTC, merged